### ISSUE TITLE
Internet Explorer issue

### ISSUE THREAD

**Issue by HelenwoodsJNCC** [jncc/web-mapper-core#85] opened 2019-06-27 13:26 UTC
Hi @andyb-esdm a number of our users are still having problems when using Internet explorer:
![image](https://user-images.githubusercontent.com/30657820/60269942-51473800-98e7-11e9-8389-bc028d8001e0.png)
I think the issue is mostly with the drag indicator icon. It only seems to affect IE users with version 11.0.126 it's not a problem in version 11.0.130.

**Comment by andyb-esdm** [comment] 2019-06-27 16:22
@HelenwoodsJNCC It looks to be worse than that. Notice that none of the icons are displaying in the toolbars either.
It may be a version problem:
11.0.126 was released on May 18th
11,0.130 was release on June 11th
Both are cumulative security updates.

But it may not be this at all. There are two different versions here but it may be because they are running on different machines and hence environments?

These icons are created using two different web fonts (angular material and font awesome).  You could have a content security policy set on the browser not allowing web fonts. There are also some known issues with displaying web fonts in ie11.

Could you possibly ask your v11.0.126 users to go to https://fontawesome.com/v4.7.0/icons/ and ask them if they can see the icons like these below? It might provide a clue.
![image](https://user-images.githubusercontent.com/31621682/60282901-e3f3d100-98ff-11e9-8845-fe19367da78c.png)

**Comment by HelenwoodsJNCC** [comment] 2019-06-28 08:44
Thanks @andyb-esdm I will get them to test it.

**Comment by HelenwoodsJNCC** [comment] 2019-06-28 08:56
@andyb-esdm they don't see any icons when they go to the above link. Does that mean that their browser probably doesn't allow web fonts?

**Comment by andyb-esdm** [comment] 2019-06-28 08:57
@HelenwoodsJNCC Thanks. Not sure it will tell us what we need to know but it's worth a try.
1. Are they at JNCC or somewhere else? 
2. Do they have access to a different browser to see if it's working on that?
3. It would be great if we could get a higher resolution screenshot too so I can see if the main font is right (this is also a web font from google).
4. And, if possible, it would be great if they could hit F12 while browsing to view the console and, if there are any errors, then send a screenshot. Appreciate that can be a bit much to ask sometimes though!

This is giving me a bit of a sense of dread ...

**Comment by andyb-esdm** [comment] 2019-06-28 08:57
@HelenwoodsJNCC sorry - we've posted across eachother.
It isn't their browser, it's probably a security policy set up by their organisation to prevent web fonts.

**Comment by hughlewiswright** [comment] 2019-06-28 08:59
@andyb-esdm it's working fine for them in Chrome, just not in IE, which unfortunately is their default browser that they all use.

**Comment by andyb-esdm** [comment] 2019-06-28 09:00
from: https://makandracards.com/makandra/42281-when-internet-explorer-does-not-render-webfonts-on-customer-machines

> IE Security Settings can prevent font download
> I had a case where the customer's IE11 would not render webfonts. It was only the customer's computer (no one else's), and only IE (Firefox worked fine). Additionally, the customer's own website that was using the same webfont files looked well—still my project did not.
> 
> The reason was IE security settings. In the "Internet Options" in the "Security" tab, there's a slider to set a security level. When set to "high", IE won't load webfonts. These settings can be customized via the "Customize" button; there's an option to (not) "Download remote fonts".
> 
> The customer's own page did render fine because it was marked as "Trusted Site" by the company's sysadmin.
> 
> Boom. I hope you'll never need to know this.

**Comment by hughlewiswright** [comment] 2019-06-28 09:06
Thanks Andy. We'll advise Defra to play with their settings (hopefully these are open to users) and we'll add an FAQ to the mapper help page.

**Comment by andyb-esdm** [comment] 2019-06-28 09:09
Thanks, Hugh. Would be good to confirm that this is the reason, though. A lot of IT departments won't change things like this.
There is an alternative, which would be to change all the icons to an image format. A bit painful, but do-able if necessary.

**Comment by andyb-esdm** [comment] 2019-06-28 09:13
@HelenwoodsJNCC @hughlewiswright Let me know what you decide. Would like to fix this for you if I can. I could put something up on our test site for people to rule this in/out.

**Comment by hughlewiswright** [comment] 2019-06-28 09:16
Thanks @andyb-esdm. We'll see if Defra can tweak settings and then decide. Is this work that can be done and deployed by next Wednesday am (launch day) or is that unrealistic?

**Comment by andyb-esdm** [comment] 2019-06-28 09:24
I can reproduce this.
![image](https://user-images.githubusercontent.com/31621682/60332486-d6d1f300-998e-11e9-804a-f1f1a9180592.png)

![image](https://user-images.githubusercontent.com/31621682/60332505-dfc2c480-998e-11e9-8000-8c13e2cc4a09.png)

**Comment by hughlewiswright** [comment] 2019-06-28 09:32
Defra bods can't access their Security tab (they can't even see it). I believe the Trusted Site options are also within this tab so that's ruled out too?

@andyb-esdm can you please proceed with mock-ups for image icons?

**Comment by andyb-esdm** [comment] 2019-06-28 12:09
@hughlewiswright @HelenwoodsJNCC 
I've created a test component that displays icons in a variety of formats.
Please can you get your Defra colleagus to visit https://jnccdev-map.esdm.co.uk/
There's a temporary panel I've put up on the map.
It has a web font icon, inline svg icon, external svg icon and a bitmap (png) icon - this is the fallback.
Could you get them  to say which icons they can see? ! What a friday :)
I'm hoping they can see the svg icons because they are scalable vectors. This will save having to make icons of different sizes for drag handles etc.

![image](https://user-images.githubusercontent.com/31621682/60341318-fc1e2b80-99a5-11e9-96a8-af22ebe0e83e.png)

**Comment by HelenwoodsJNCC** [comment] 2019-06-28 12:49
@andyb-esdm two response so far indicating they can see all the symbols except the web font.

**Comment by andyb-esdm** [comment] 2019-06-28 12:52
@HelenwoodsJNCC okay - that will do I think - thank you - looks like we can go for svg - the  icons won't be exactly the same but should be smart and similar enough

**Comment by hughlewiswright** [comment] 2019-06-28 13:12
That's great to hear Andy thank you. Helen is now on leave for the next two weeks but myself and Jordan will be your main contacts in the meantime. I'm planning our remaining tasks before launch day on Weds - do you think the icons can be sorted by then?

**Comment by andyb-esdm** [comment] 2019-06-28 13:14
They will be done, Hugh

**Comment by hughlewiswright** [comment] 2019-06-28 13:15
Top man, thank you very much

**Comment by GMDuncan** [comment] 2019-06-28 13:27
Just adding confirmation from Natural England that SVG gets through their end too.

**Comment by andyb-esdm** [comment] 2019-06-28 15:53
@HelenwoodsJNCC  @GMDuncan @hughlewiswright 
I've replaced all the web font references with custom svg icons from https://materialdesignicons.com/
I know it's a bit late, but if anyone who was having problems before could confirm everything is displaying properly now, that would be great.
Unfortunately, I haven't got quite the same control over these images as I did with the font, so I don't think they feel quite as consistent and well-aligned - especially the bottom right toolbar. But hopefully, this is good enough to get you through the launch and perhaps we can revisit this later.

**Comment by hughlewiswright** [comment] 2019-06-28 15:58
I can see those changes at our end and they're looking good. I've contacted our testers at Defra but they may have already gone home. We'll try others on Monday. Thanks for dropping everything to sort this one.

**Comment by andyb-esdm** [comment] 2019-06-28 16:07
You're welcome.
I tested as I went along but it was a large number of edits including changing buttons that make function calls. It would be good if someone from JNCC could do a quick test before launch too.
The main things to test are:
- the tooltips are all correct
- clicking on any of the icons does the same thing they used to!
- the icons change to reflect state (e.g. expanded trees or panels, filter state etc.)

**Comment by hughlewiswright** [comment] 2019-06-28 16:10
Sure. I'll get onto that on Monday. No response from Defra yet so I'm presuming they've gone home. Have a good weekend - it's well deserved!

**Comment by hughlewiswright** [comment] 2019-07-01 08:32
Morning @andyb-esdm . There's good news and bad news. The good news is that the tool functions are all working for me. The bad news is there's now an issue with the toolbar in the bottom-right of the mapper not displaying properly for Defra, NE and Welsh Gov. It appears stretched and only shows 5 of the 9 tools. I can't replicate this issue by disabling "download web fonts". See the image attached. The 5 tools that are visible are working normally.

![ToolbarStretch](https://user-images.githubusercontent.com/46788267/60421537-f0b74400-9be1-11e9-8019-71d679808d98.png)

On a more minor note - can you change the colour of the "not currently downloadable" symbol from red to a pale grey please? The red stands out and rather over-emphasises one of our shortfalls.

Thanks

**Comment by andyb-esdm** [comment] 2019-07-01 08:46
Oh dear, we're not out of the woods yet it seems ... 
I found another issue in ie11 only too. The opacity slider popup is positioned incorrectly. It looks to be because of the layer sidebar. It's positioning as if this is always closed.
These are ie11 bugs with the positioning strategy we're using. The opacity slider may not be something I can fix directly with styling. I may have to put it on the layer control itself.

**Comment by andyb-esdm** [comment] 2019-07-01 08:48
@hughlewiswright are you able to replicate the toolbar stretching locally on ie11?

**Comment by hughlewiswright** [comment] 2019-07-01 08:49
No not yet.

**Comment by andyb-esdm** [comment] 2019-07-01 09:07
@hughlewiswright Do you mean that you're not getting the stretching effect or you haven't tested on ie11?

**Comment by hughlewiswright** [comment] 2019-07-01 09:10
Sorry, I have tested it on my version of IE11 but I'm not getting the stretching effect. Can you recommend any Internet Options I should play with to try and replicate it? 

If it helps, I am using IE11 version 11.829.17134.0. Defra have version 11.0.9600.19374CO and Welsh Gov have version 11.3024.14393.0.

**Comment by andyb-esdm** [comment] 2019-07-01 09:12
Thanks.
Unfortunately, the internet option, if it existed, would be "align icons in a broken manner" ;)

**Comment by andyb-esdm** [comment] 2019-07-01 09:25
@hughlewiswright can you get a Defra/Welsh Gov colleague to test again at https://mapper.mpa.jncc.gov.uk/ ?

**Comment by hughlewiswright** [comment] 2019-07-01 09:37
@andyb-esdm Welsh Gov reporting no change. Waiting to hear from Defra.

**Comment by GMDuncan** [comment] 2019-07-01 09:38
Checking with NE also.

**Comment by andyb-esdm** [comment] 2019-07-01 09:45
If it hasn't changed for Welsh Gov then it's no good. Hmm. This was a reported scaling issue with svg icons in some versions of ie11. I was sure it was going to work. I'll try something else.

**Comment by hughlewiswright** [comment] 2019-07-01 09:46
It's working for Defra!

**Comment by hughlewiswright** [comment] 2019-07-01 09:55
Welsh Gov now say it's ok. Think they just needed a proper refresh

**Comment by andyb-esdm** [comment] 2019-07-01 09:55
Great - I was doing terrible, sinful things to the html here!

**Comment by andyb-esdm** [comment] 2019-07-01 10:08
@hughlewiswright @GMDuncan 
Okay the remaining issue is the opacity pop-up positioning in ie11. I'm sorry but I won't have time to address this today and I don't think I will be able to fix it directly (but I'll try). In the likely event I can't fix it, we could change it from a pop-up to a div that becomes visible in the layer control itself. A bit like this?

![image](https://user-images.githubusercontent.com/31621682/60428301-7641f080-9bf0-11e9-8e7d-9d15f587aaa2.png)

Any thoughts on this or alternative suggestions?

**Comment by GMDuncan** [comment] 2019-07-01 10:15
I actually quite like that personally as a default behaviour - Hugh's call though! Just commenting here to see if @helen-lillis thinks it could be a worthwhile change for the EMODnet mapper too?

**Comment by andyb-esdm** [comment] 2019-07-01 10:17
@GMDuncan It will need to be 'both' mappers of course (it's the same code). So, yes, will need EMODnet to be happy too. The opacity button would toggle visibility of the slider. Hopefully, this won't have an collateral on positioning of the active layers - something I would need to test.

**Comment by GMDuncan** [comment] 2019-07-01 10:24
Confirming that the toolbar looks fine on Natural England machines.

**Comment by andyb-esdm** [comment] 2019-07-01 10:25
@GMDuncan Thanks for the update. Nearly there ...

**Comment by helen-lillis** [comment] 2019-07-01 10:27
Yes I'd be happy with that alternative for the EMODnet mapper.

**Comment by hughlewiswright** [comment] 2019-07-01 10:34
@andyb-esdm wrt. opacity, that solution looks very neat. Would the bar only be visible once the opacity tool is clicked, or would it be permanent?

**Comment by hughlewiswright** [comment] 2019-07-01 10:41
@andyb-esdm Thank you very much for your additional fixes this morning, they look great. 
I have one more minor fix please - can you change the default text that displays in gazetteer search box from "Search for marine regions..." to "Search for a Marine Protected Area..."?

**Comment by helen-lillis** [comment] 2019-07-01 10:45
would that affect the EMODnet mapper's search bar too?

**Comment by andyb-esdm** [comment] 2019-07-01 10:46
@hughlewiswright 
The idea with the opacity tool is that it toggles on and off. However, this might break positioning so I'll need to test it. We really don't want to have it on all the time because it will take up a lot of extra space for each layer and it's already getting a bit tight.

For the text, "Search for Marine Protected Area" would apply only to the MPA mapper presumably (not EMODnet)? If so, then we would need to make it a configuration option.

**Comment by andyb-esdm** [comment] 2019-07-01 10:46
@helen-lillis (hello by the way). Yes it would.

**Comment by helen-lillis** [comment] 2019-07-01 10:47
@andyb-esdm (hello :)) yes we wouldn't want it to say that for EMODnet

**Comment by hughlewiswright** [comment] 2019-07-01 10:50
Agreed and in that case can we make it a configuration option please? 

Also agree about plans for opacity tool and not have the bar on all the time.

**Comment by andyb-esdm** [comment] 2019-07-01 10:51
rightio - should find time to do this by tomorrow

**Comment by hughlewiswright** [comment] 2019-07-01 10:54
Many thanks

**Comment by andyb-esdm** [comment] 2019-07-02 11:05
@hughlewiswright @helen-lillis @GMDuncan 
Could you and your IE11 users please take a look at: https://jnccdev-map.esdm.co.uk/
I've changed the behaviour of the opacity slider as described above.
Let me know what you think before I (literally) commit to this.
Thanks.
I'll work on the search text config in the meantime.

**Comment by hughlewiswright** [comment] 2019-07-02 11:12
@andyb-esdm will do!

**Comment by hughlewiswright** [comment] 2019-07-02 11:23
@andyb-esdm it's working fine here at JNCC and at Defra. I won't be able to confirm Welsh Gov until later this afternoon, so you may wish to proceed. It looks really neat by the way.

**Comment by andyb-esdm** [comment] 2019-07-02 11:40
@hughlewiswright Glad it's okay.

I've implemented a new configurable option: gazetteerPlaceholder . This displays "Search for marine regions ..." for EMODnet and "Search for Marine Protected Area ..." for MPA. You can set it to whatever you like in future in the application config file. If the options isn't present in the config file, it defaults to "Search for marine regions ..."

I've deployed to MPA staging.

Hope this is everything you needed for launch. Good luck with it.

**Comment by hughlewiswright** [comment] 2019-07-02 12:36
@andyb-esdm Thanks for making that edit and deploying it. 

I don't suppose you could edit the text on the MPA gazetteerPlaceholder to add an "a" between the "for" and the "Marine" in "Search for a Marine Protected Area..." please? I can't change the config file myself and I don't have anyone else to ask at the moment. Sorry.

**Comment by andyb-esdm** [comment] 2019-07-02 12:47
@hughlewiswright that's done

**Comment by hughlewiswright** [comment] 2019-07-02 12:49
Thank you @andyb-esdm. Let's close this issue quick before anyone finds anything else!

**Comment by andyb-esdm** [comment] 2019-07-02 12:50
:) good plan

**Comment by hughlewiswright** [comment] 2019-07-05 14:14
I'm very sorry to have reopened this issue Andy. It's probably best to ignore this until next week...
We've got some (delayed) feedback from Welsh Gov about an icon size issue in the Active Layers window when a new layer is added to the mapper (in IE).  I am not seeing this in my version of IE. It looks like the icons are the right ones, just squashed.

![MiniIcons](https://user-images.githubusercontent.com/46788267/60728036-4881e200-9f37-11e9-88b0-f70800947c71.jpg)

**Comment by andyb-esdm** [comment] 2019-07-05 14:25
@hughlewiswright could you get them to test again at https://mapper.mpa.jncc.gov.uk/ ?
Tell them to make sure they've refreshed their browser first.

There was some scaling on these icons and that's what gave the issue in the controls toolbar. So I've removed the scaling. It means the icons are a bit bigger though.

Anyway, let's see if it works.

Fallback would be to change all the icons again to png format but that would take me a while.

**Comment by hughlewiswright** [comment] 2019-07-05 14:39
@andyb-esdm Thanks for picking this up straight away. I've asked them to test it again.

**Comment by hughlewiswright** [comment] 2019-07-05 15:05
@andyb-esdm Welsh Gov have confirmed that this is fixed. Thanks and feel free to close the issue again.

**Comment by andyb-esdm** [comment] 2019-07-05 15:07
@hughlewiswright That's good. I assume you don't mind that the icons are a bit bigger.

**Comment by hughlewiswright** [comment] 2019-07-05 15:09
Certainly not for the time being thanks @andyb-esdm.

**Closed** 2019-07-05 15:09 UTC
