### ISSUE TITLE
Data download links

### ISSUE THREAD

**Issue by andyb-esdm** [jncc/web-mapper-core#29] opened 2019-01-29 12:38 UTC
**Database/API:** include a download url for each layer configuration that can take you to a download page or point directly at a zip file so that the user can download the layer data.

**UI:** if url present in configuration, display a link or button next to the layer that opens the download page in another tab or directly downloads the data file.

**Comment by andyb-esdm** [comment] 2019-01-30 15:18
@JordanPinder can you confirm that the specification here is just for a url for download? Clicking on the download link will take you to a new tab with the downloads available in a separate website.

**Comment by JordanPinder** [comment] 2019-01-30 15:48
@andyb-esdm for the EMODnet mapper it is a simple url link to the download data page as we require users to fill in the details before downloading. An [example is this link](https://www.emodnet-seabedhabitats.eu/access-data/download-data/?linkid=1) which has EUSeaMap pre-selected. 

The MPA mapper seems to be a direct download for some layers - @HelenwoodsJNCC can you just confirm that?

**Comment by andyb-esdm** [comment] 2019-01-30 16:00
@JordanPinder Thank you. I don't think a link to a page or a link to a file will make much difference from the point of view of the mapper. If it's a page, we can have it open in a new tab. If it's a file, then you should automatically get a prompt in your browser to download it.

**Comment by JordanPinder** [comment] 2019-01-30 16:04
@andyb-esdm ah wonderful! If it's not an issue having both then that's grand.

**Comment by andyb-esdm** [comment] 2019-01-30 16:20
@JordanPinder We'll test this and confirm asap.

**Comment by HelenwoodsJNCC** [comment] 2019-01-31 09:00
@JordanPinder @andyb-esdm I can confirm the MPA mapper has some download links that are simple url links to other data download pages, and others that are a direct download of zipped files. From reading the above that doesn't seem to be a problem though.

**Comment by andyb-esdm** [comment] 2019-01-31 09:04
@HelenwoodsJNCC Yes. Pretty confident that won't be an issue.

**Comment by andyb-esdm** [comment] 2019-03-04 17:48
Implemented

**Comment by HelenwoodsJNCC** [comment] 2019-03-19 08:24
@andyb-esdm Can we make it so there is always a download button but it is greyed out if not data download link is available? Then we can have a tool tip stating 'Not currently downloadable'.

**Comment by andyb-esdm** [comment] 2019-03-19 12:23
@HelenwoodsJNCC okay.

**Comment by andyb-esdm** [comment] 2019-03-19 13:01
@HelenwoodsJNCC implemented. Please test.

**Comment by HelenwoodsJNCC** [comment] 2019-03-19 13:25
Seems to be working fine.

**Comment by JordanPinder** [comment] 2019-03-21 15:59
Issue resolved, closing.

**Closed by JordanPinder** 2019-03-21 15:59 UTC
Labels: area: Layer control, ~ Partially Ready for test
